gemfile:
- gemfiles/fluentd_0.14.gemfile
rvm:
  - "2.1"
  - "2.2"
  - "2.3.0"
before_install:
  - gem update bundler
addons:
  code_climate:
    repo_token: bf148eb6cb4ff9ae6666bd12aab208c0aff2e42e29be855b89aac890a3dd946e
after_success:
  - bundle exec codeclimate-test-reporter
